apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: decisions.operator.baaas
spec:
  group: operator.baaas
  names:
    kind: Decision
    listKind: DecisionList
    plural: decisions
    singular: decision
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Version
      type: string
      description: Current decision revision
      JSONPath: .status.versionId
    - name: Endpoint
      type: string
      description: Decision endpoint
      JSONPath: .status.endpoint