apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: decisionversions.operator.baaas
spec:
  group: operator.baaas
  names:
    kind: DecisionVersion
    listKind: DecisionVersionList
    plural: decisionversions
    singular: decisionversion
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  subresources:
    status: {}