apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: decisionrequests.operator.baaas
spec:
  group: operator.baaas
  names:
    kind: DecisionRequest
    listKind: DecisionRequestList
    plural: decisionrequests
    singular: decisionrequest
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true