apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: decisions.operator.baaas
spec:
  group: operator.baaas
  names:
    kind: Decision
    listKind: DecisionList
    plural: decisions
    singular: decision
    categories:
      - all
      - baaas
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Version
      type: string
      description: Current decision revision
      JSONPath: .status.versionId
    - name: Endpoint
      type: string
      description: Decision endpoint
      JSONPath: .status.endpoint
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
            - definition
          properties:
            definition:
              type: object
              required:
                - version
                - source
                - kafka
              properties:
                version:
                  type: string
                source:
                  type: string
                kafka:
                  type: object
                  required:
                    - bootstrapServers
                    - secretName
                  properties:
                    bootstrapServers:
                      type: string
                    secretName:
                      type: string
                    inputTopic:
                      type: string
                    outputTopic:
                      type: string
                env:
                  type: object
            webhooks:
              type: array
              items:
                type: string