apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: decisions.operator.baaas
spec:
  group: operator.baaas
  names:
    kind: Decision
    listKind: DecisionList
    plural: decisions
    singular: decision
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true