apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: decisionversions.operator.baaas
spec:
  group: operator.baaas
  names:
    kind: DecisionVersion
    listKind: DecisionVersionList
    plural: decisionversions
    singular: decisionversion
    categories:
      - all
      - baaas
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Ready
      type: string
      description: Ready
      JSONPath: .status.conditions[?(@.type=='Ready')].status
    - name: Build
      type: string
      description: Build status
      JSONPath: .status.conditions[?(@.type=='Build')].reason
    - name: Service
      type: string
      description: Kogito Service status
      JSONPath: .status.conditions[?(@.type=='Service')].reason
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
            - version
            - source
            - kafka
          properties:
            version:
              type: string
            source:
              type: string
            kafka:
              type: object
              required:
                - bootstrapServers
                - secretName
              properties:
                bootstrapServers:
                  type: string
                secretName:
                  type: string
                inputTopic:
                  type: string
                outputTopic:
                  type: string
            env:
              type: object