---
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=/maven/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s $CI_PROJECT_DIR/.ci/settings.xml --batch-mode"
  OUTPUT_CONTAINER_NAME: "quay.io/rblake/baaas-cluster-control-plane:$CI_COMMIT_SHA"

stages:
  - build
  - test
  - deploy-jars
  - native-compile
  - build-and-push-container

.cache-definition: &cache-definition
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - api/target
      - cluster-control-plane-operator/target

build:
  <<: *cache-definition
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: build
  script:
    - "/usr/share/maven/bin/mvn compile"
  artifacts:
    expire_in: 1 week
    paths:
      - api/target/checkstyle.log
      - cluster-control-plane-operator/target/checkstyle.log
  tags:
    - baaas
  only:
    - main@baaas/baaas-cluster-control-plane
    - merge_requests@baaas/baaas-cluster-control-plane

test:
  <<: *cache-definition
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: test
  script:
    - "/usr/share/maven/bin/mvn test"
  artifacts:
    expire_in: 1 week
    reports:
      junit:
        - api/target/surefire-reports/TEST-*.xml
  tags:
    - baaas
  only:
    - main@baaas/baaas-cluster-control-plane
    - merge_requests@baaas/baaas-cluster-control-plane

deploy-jars:
  <<: *cache-definition
  image: quay.io/rblake/baaas-maven-kogito-s2i:6888c2304eeeb3b45740576325571ba8a1d2b4ed
  stage: deploy-jars
  script:
    - "/usr/share/maven/bin/mvn -s .m2/settings.xml package deploy -Dmaven.test.skip=true -Dcheckstyle.skip"
  tags:
    - baaas
  only:
    - main@baaas/baaas-cluster-control-plane

native-compile:
  <<: *cache-definition
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: native-compile
  script:
    - "/usr/share/maven/bin/mvn package -Pnative -Dmaven.test.skip=true"
  artifacts:
    expire_in: 1 week
    paths:
      - cluster-control-plane-operator/target/*-runner
  tags:
    - baaas
  only:
    - main@baaas/baaas-cluster-control-plane
    - merge_requests@baaas/baaas-cluster-control-plane

build-and-push-container:
  image: docker:19.03.12
  stage: build-and-push-container
  before_script:
    - echo "$CONTAINER_REGISTRY_PASSWORD" | docker login quay.io --username $CONTAINER_REGISTRY_USER --password-stdin
  script:
    - "docker build -f cluster-control-plane-operator/src/main/docker/Dockerfile.native -t $OUTPUT_CONTAINER_NAME cluster-control-plane-operator/"
    - "docker push $OUTPUT_CONTAINER_NAME"
  after_script:
    - "docker image rm -f $OUTPUT_CONTAINER_NAME"
  tags:
    - baaas
  only:
    - main@baaas/baaas-cluster-control-plane
