---
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=/maven/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s $CI_PROJECT_DIR/.ci/settings.xml --batch-mode"
  OUTPUT_CONTAINER_NAME: "quay.io/rblake/baaas-decision-fleet-shard:$CI_COMMIT_SHA"

stages:
  - build
  - test
  - deploy-jars
  - native-compile
  - build-and-push-container

include:
  - local: '.cd-allowlist.yml'

.cache-definition: &cache-definition
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - api/target
      - decision-fleet-shard-operator/target

build:
  <<: *cache-definition
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: build
  script:
    - "/usr/share/maven/bin/mvn package -Dmaven.test.skip=true -Pvalidate-formatting"
  tags:
    - baaas
  only:
    refs:
      - main@baaas/baaas-decision-fleet-shard
      - merge_requests@baaas/baaas-decision-fleet-shard

test-openshift:
  <<: *cache-definition
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: test
  script:
    - "/usr/share/maven/bin/mvn test -Dbaaas.k8s.platform=openshift"
  artifacts:
    expire_in: 1 week
    reports:
      junit:
        - api/target/surefire-reports/TEST-*.xml
  tags:
    - baaas
  only:
    refs:
      - main@baaas/baaas-decision-fleet-shard
      - merge_requests@baaas/baaas-decision-fleet-shard

test-kubernetes:
  <<: *cache-definition
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: test
  script:
    - "/usr/share/maven/bin/mvn test -Dbaaas.k8s.platform=k8s"
  artifacts:
    expire_in: 1 week
    reports:
      junit:
        - api/target/surefire-reports/TEST-*.xml
  tags:
    - baaas
  only:
    refs:
      - main@baaas/baaas-decision-fleet-shard
      - merge_requests@baaas/baaas-decision-fleet-shard

deploy-jars:
  <<: *cache-definition
  extends: .cd-allowlist
  image: quay.io/rblake/baaas-maven-kogito-s2i:6888c2304eeeb3b45740576325571ba8a1d2b4ed
  stage: deploy-jars
  script:
    - "/usr/share/maven/bin/mvn -s .m2/settings.xml package deploy -Dmaven.test.skip=true -Dcheckstyle.skip"
  tags:
    - baaas
  only:
    refs:
      - main@baaas/baaas-decision-fleet-shard

native-compile:
  <<: *cache-definition
  extends: .cd-allowlist
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: native-compile
  script:
    - "/usr/share/maven/bin/mvn package -Pnative -Dmaven.test.skip=true"
  artifacts:
    expire_in: 1 day
    paths:
      - decision-fleet-shard-operator/target/*-runner
  tags:
    - baaas
  only:
    refs:
      - main@baaas/baaas-decision-fleet-shard
      - merge_requests@baaas/baaas-decision-fleet-shard

build-and-push-container-jvm:
  <<: *cache-definition
  extends: .cd-allowlist
  image: docker:19.03.12
  stage: build-and-push-container
  before_script:
    - echo "$CONTAINER_REGISTRY_PASSWORD" | docker login quay.io --username $CONTAINER_REGISTRY_USER --password-stdin
  script:
    - "docker build -f decision-fleet-shard-operator/src/main/docker/Dockerfile.jvm -t $OUTPUT_CONTAINER_NAME-jvm decision-fleet-shard-operator/"
    - "docker push $OUTPUT_CONTAINER_NAME-jvm"
  after_script:
    - "docker image rm -f $OUTPUT_CONTAINER_NAME-jvm"
  tags:
    - baaas
  only:
    refs:
      - main@baaas/baaas-decision-fleet-shard

build-and-push-container-native:
  image: docker:19.03.12
  extends: .cd-allowlist
  stage: build-and-push-container
  before_script:
    - echo "$CONTAINER_REGISTRY_PASSWORD" | docker login quay.io --username $CONTAINER_REGISTRY_USER --password-stdin
  script:
    - "docker build -f decision-fleet-shard-operator/src/main/docker/Dockerfile.native -t $OUTPUT_CONTAINER_NAME decision-fleet-shard-operator/"
    - "docker push $OUTPUT_CONTAINER_NAME"
  after_script:
    - "docker image rm -f $OUTPUT_CONTAINER_NAME"
  tags:
    - baaas
  only:
    refs:
      - main@baaas/baaas-decision-fleet-shard
