apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  application.properties: |-

    mp.messaging.incoming.kogito_incoming_stream.connector=smallrye-kafka
    mp.messaging.incoming.kogito_incoming_stream.topic=${BAAAS_KAFKA_INCOMING_TOPIC}
    mp.messaging.incoming.kogito_incoming_stream.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    mp.messaging.outgoing.kogito_outgoing_stream.connector=smallrye-kafka
    mp.messaging.outgoing.kogito_outgoing_stream.topic=${BAAAS_KAFKA_OUTGOING_TOPIC}
    mp.messaging.outgoing.kogito_outgoing_stream.value.serializer=org.apache.kafka.common.serialization.StringSerializer
