apiVersion: operator.baaas/v1alpha1
kind: DecisionRequest
metadata:
  name: example-decision-request-2
spec:
  customerId: kermit
  name: example-decision
  definition:
    version: "2"
    source: 's3://baaas-storage-dev/customers/example/example-decision/1/dmn.xml'
  webhooks:
    - http://my-server.example.com/callback?foo