apiVersion: operator.baaas/v1alpha1
kind: DecisionRequest
metadata:
  name: kafka-decision
spec:
  customerId: kermit
  name: kafka-decision
  definition:
    version: "1"
    source: 's3://baaas-storage-dev/customers/example/example-decision/1/dmn.xml'
    kafka:
      bootstrapServers: ruben-kafk--ovs-eyepvmzenltefb-tnk-wjf.kafka.devshift.org:443
      secretName: baaas-ccp-kafka-auth
      inputTopic: theinput
      outputTopic: theoutput
  webhooks:
    - http://localhost:18080/callback