apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: baaas-ccp-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: cluster-control-plane
    namespace: ruben-baaas-operator
roleRef:
  kind: ClusterRole
  name: baaas-ccp-cluster-role
  apiGroup: rbac.authorization.k8s.io