#name: Decision Fleet Shard
#on:
#  push:
#    branches:
#      - main
#jobs:
#  decision-fleetshard-build:
#    env:
#      MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
#      MAVEN_CLI_OPTS: -s ${{ github.workspace }}/.ci/settings.xml --batch-mode
#      OUTPUT_CONTAINER_NAME: quay.io/kiegroup/baaas-decision-fleet-shard:${{ github.sha }}
#    concurrency:
#      group: baaas-dfs-main-${{ github.head_ref }}
#      cancel-in-progress: true
#    timeout-minutes: 30
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up GraalVM
#        uses: DeLaGuardo/setup-graalvm@4.0
#        with:
#          graalvm: '20.3.2'
#          java: 'java11'
#      - name: Install native-image Binary
#        shell: bash
#        run: gu install native-image
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Cache Maven Packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#
